swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
- name: "auth"
  description: "For authentication and registration"
- name: "file"
  description: "For file operation like view, upload, remove, modify"
schemes:
- "https"
- "http"
paths:
  /auth/register:
    post:
      tags:
      - "auth"
      summary: "register a user"
      description: ""
      operationId: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "username and password"
        required: true
        schema:
          $ref: "#/definitions/MyUser"
      responses:
        "200":
          description: "registration complate"


  /auth/authenticate:
    post:
      tags:
      - "auth"
      summary: "gets usrname and password. returns JWT token"
      description: ""
      operationId: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "username and password"
        required: true
        schema:
          $ref: "#/definitions/AuthenticationRequest"
      responses:
        "200":
          description: "return string JWT token"

  /file/upload:
    post:
      tags:
      - "file"
      summary: "gets MultipartFile and save file to server. save file info to DB"
      responses:
        "200":
          description: "return string JWT token"
          schema:
            $ref: "#/definitions/FileInfo"          
  /file/info/all:
    get:
      tags:
      - "file"
      summary: "return FileInfo Array which belongs to user"
      responses:
        "200":
          description: ""
          schema:
            $ref: "#/definitions/FileInfo"  
  /file:
    get:
      tags:
      - "file"
      summary: "gets file ID and return file as a byte array"
      responses:
        "200":
          description: "return file as a byte array"
      parameters:
      - in: "formData"
        type: number
        name: "fileId"
        required: true
  /file/rename:
    put:
      tags:
      - "file"
      summary: "get file ID and new file name. Return modified file info"
      responses:
        "200":
          description: "Modified file info"
  /file/delete:
    delete:
      tags:
      - "file"
      summary: "gets file ID. return deleted file info"
      responses:
        "200":
          description: "Modified file info"
          schema:
            $ref: "#/definitions/FileInfo"            


securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  MyUser:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      password:
        type: "string"        
      role:
        type: "string"
  AuthenticationRequest:
    type: "object"
    properties:
      username:
        type: "string"
      password:
        type: "string"
  FileInfo:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      userId:
        type: "integer"
        format: "int64"        
      name:
        type: "string"
      path:
        type: "string"        
      extension:
        type: "string"
      size:
        type: "integer"
        format: "int64"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"